apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "uptainer.fullname" . }}
  labels:
    {{- with .Values.podLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  schedule: "{{ .Values.schedule }}"
  concurrencyPolicy: Forbid
  timeZone: "{{ .Values.timezone }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: uptainer
            securityContext:
              {{- toYaml .Values.securityContext | nindent 14 }}
            image: "{{ .Values.image.repository }}:v{{ .Values.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            env:
              - name: GITHUB_API_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: uptainer-provider-tokens
                    key: github
              - name: DOCKERHUB_API_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: uptainer-provider-tokens
                    key: dockerhub
            command:
              - /app/.local/bin/uptainer
              - --config-file
              - /etc/uptainer/config.yaml
            resources:
              {{- toYaml .Values.resources | nindent 14 }}
            {{- with .Values.volumeMounts }}
            volumeMounts:
              {{- toYaml . | nindent 14 }}
            {{- end }}
          restartPolicy: OnFailure
          {{- with .Values.volumes }}
          volumes:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 10 }}
          {{- end }}
          