apiVersion: v1    
kind: Secret
metadata:
  name: {{ include "uptainer.fullname" . }}-provider-tokens
type: Opaque
stringData:
  github: {{ .Values.provider_tokens.github }}
  dockerhub: {{ .Values.provider_tokens.dockerhub }}