# Default values for uptainer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: ghcr.io/asbarbati/uptainer
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  # Checkout on the Chart.yaml
  tag: ""

# This is for the secretes for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

#This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Automatically mount a ServiceAccount's API credentials?
  automount: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/ 
podAnnotations: {}
# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

podSecurityContext:
  fsGroup: 1000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

resources:
  limits:
    cpu: 100m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

# This config below are mandatory
volumes:
  - name: tmpdir
    emptyDir:
      sizeLimit: 512Mi
  - name: sshkey
    secret:
      secretName: mysupersecretkey
  - name: configfile
    configMap:
      name: uptainer-config
      items:
        - key: config
          path: config.yaml
volumeMounts: 
  - name: tmpdir
    mountPath: "/tmp"
  - name: sshkey
    mountPath: "/app/.ssh/id_rsa"
    readOnly: true
  - name: configfile
    mountPath: "/etc/uptainer"
    readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}

schedule: "30 04 * * *"
timezone: "Europe/Rome"

# Checkout on the Docs https://uptainer.readthedocs.io/config.html
configfile: |
  repos:
    - name: My super project
      image_repository: ghcr.io/immich-app/immich-server
      git_ssh_url: git@gitlab.example:main/myrepo.repo
      git_ssh_privatekey: /app/.ssh/id_rsa/ssh-privatekey
      git_branch: main
      git_values_filename: values.yaml
      values_key: image.tag
      version_match: v1.[0-9]+.[0-9]+

# Create the secret using
# kubectl create secret generic my-secret --from-file=ssh-privatekey=/path/to/.ssh/id_rsa

provider_tokens:
  github: ""
  dockerhub: ""

# DEBUG MODE 1/0
debugmode: 0